version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: cws-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: content-workflow
    volumes:
      - mongodb_data:/data/db
    networks:
      - cws-network

networks:
  cws-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local